/* 把每個actin type的字串儲存為變數，方便使用 */
// 有三種狀況

const GENERATION = {
  FETCH: "GENERSTION_FETCH",
  FETCH_ERROR: "GENERATION_FETCH_ERROR",
  FETCH_SUCCESS: "GENERATION_FETCH_SUCCESS",
};

const DRAGON = {
  FETCH: "DRAGON_FETCH",
  FETCH_ERROR: "DRAGON_FETCH_ERROR",
  FETCH_SUCCESS: "DRAGON_FETCH_SUCCESS",
};

const ACCOUNT = {
  FETCH: "ACCOUNT_FETCH",
  FETCH_ERROR: "ACCOUNT_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_FETCH_SUCCESS",
  FETCH_LOGOUT_SUCCESS:"FETCH_LOGOUT_SUCCESS",
  FETCH_AUTHENTICATED_SUCCESS: 'FETCH_AUTHENTICATED_SUCCESS'
};

const ACCOUNT_DRAGONS ={
  FETCH: "ACCOUNT_DRAGON_FETCH",
  FETCH_ERROR: "ACCOUNT_DRAGON_FETCH_ERROR",
  FETCH_SUCCESS: "ACCOUNT_DRAGON_FETCH_SUCCESS",
}

export { ACCOUNT, GENERATION, DRAGON, ACCOUNT_DRAGONS };